import type { Reel } from './reelsData';

export const INDIA_CURATED_REELS: Reel[] = [
  // -------------------------------------------------------------
  // 1. Delhi NCR - Ghaziabad
  // -------------------------------------------------------------
  {
    id: "post-276040517834610119306",
    city: "Ghaziabad, IN",
    restaurant: "Chawri Bazar / Ghantaghar Winter Cart",
    reel_url: "https://www.facebook.com/reel/2544643095960474/",
    creator_handle: "@chawribazar_delhi",
    protein: "8g",
    fiber: "1g",
    calories: "130",
    sugar: "11g",
    caption_for_app: "Daulat Ki Chaat Rs 50 — Foam dessert, melts in 5 mins, winter only - can't deliver",
    caption: "Daulat Ki Chaat Rs 50 Chawri Bazar — Foam dessert, melts in 5 mins, winter only - can't deliver",
    views: "245k",
    type: "real",
    dish_name: "Daulat ki Chaat + Millet Momos",
    thumbnail: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "winter-delicacy", "delhi-ncr", "ghaziabad", "street-heritage", "zero-oil"],
    eating_type: "creator eating fresh foam on leaf cup outside",
    cooking_fat: "Zero Oil / Whipped Milk Dew Foam",
    verified: true,
    why: "Foam dessert, melts in 5 mins, winter only - can't deliver",
    why_off_delivery: "Foam dessert, melts in 5 mins, winter only - can't deliver",
    price: 50,
  },
  {
    id: "post-429713494984221286417",
    city: "Delhi, IN",
    restaurant: "Millet Momos Cart Network (Athlete Founded)",
    reel_url: "https://www.instagram.com/reel/DWY1gesktQB/",
    creator_handle: "@milletmomos_india",
    protein: "18g",
    fiber: "9g",
    calories: "210",
    sugar: "1g",
    caption_for_app: "Millets Momos — 30 carts across Delhi NCR made by former athletes, 100% maida-free & steamed",
    caption: "Millets Momos - 30 outlets Delhi NCR from cart — Former athletes making maida-free millet momos",
    views: "380k",
    type: "real",
    dish_name: "Steamed Ragi & Jowar Millet Momos",
    thumbnail: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "millet-diet", "steamed", "delhi-ncr", "high-protein", "maida-free"],
    eating_type: "creator eating piping hot steamed millet momos at cart",
    cooking_fat: "100% Steamed / Zero Added Oil",
    verified: true,
    why: "Former athletes making maida-free millet momos",
    why_off_delivery: "Former athletes making maida-free millet momos (30 street carts across Delhi NCR)",
    price: 80,
  },
  {
    id: "post-410777250410216779171",
    city: "Delhi, IN",
    restaurant: "Anita's Salad Delhi (Green Park / Lajpat)",
    reel_url: "https://www.instagram.com/reel/Db3WNa0Cwmq/",
    creator_handle: "@anitassalad",
    protein: "15g",
    fiber: "12g",
    calories: "175",
    sugar: "3g",
    caption_for_app: "Healthy Sprouts Salad — Live tossed sprouts, pomegranate, crunchy corn & seed mix from Anita's diet cart",
    caption: "Healthy Sprouts Salad - Anita's Salad Delhi — Live tossed sprouts, pomegranate, corn - premium diet cart",
    views: "290k",
    type: "real",
    dish_name: "Anita's Live Sprout & Pomegranate Salad Bowl",
    thumbnail: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "live-tossed", "raw-vegan", "delhi", "high-fiber", "clean-eating"],
    eating_type: "creator eating freshly tossed rainbow sprouts salad",
    cooking_fat: "Cold-Pressed Lemon Dressing / Zero Oil",
    verified: true,
    why: "Live tossed sprouts, pomegranate, corn - premium diet cart",
    why_off_delivery: "Live tossed sprouts, pomegranate, corn - premium diet cart",
    price: 60,
  },

  // -------------------------------------------------------------
  // 2. Mumbai
  // -------------------------------------------------------------
  {
    id: "post-418271085422263857894",
    city: "Mumbai, IN",
    restaurant: "Matunga & Fort Heritage Breakfast Carts",
    reel_url: "https://www.instagram.com/reel/DcllJYcoIX7/",
    creator_handle: "@curlytales",
    protein: "14g",
    fiber: "8g",
    calories: "210",
    sugar: "2g",
    caption_for_app: "Healthy Breakfast Mumbai under Rs 100 — Poha Rs 40, Idli Sambar Rs 50, Khaman Dhokla Rs 40 (steamed, live cart)",
    caption: "Healthy Breakfast Mumbai under 100 - Curly Tales — Poha 40, Idli Sambar 50, Dhokla 40 - steamed, live cart",
    views: "640k",
    type: "real",
    dish_name: "Poha / Idli-Sambar / Dhokla Healthy Breakfast",
    thumbnail: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "mumbai-street", "steamed", "breakfast", "under-100", "healthy-staple"],
    eating_type: "creator eating fresh steamed idli sambar and poha on footpath",
    cooking_fat: "Steamed / Mustard & Curry Leaf Tempering",
    verified: true,
    why: "Poha 40, Idli Sambar 50, Dhokla 40 - steamed, live cart",
    why_off_delivery: "Poha 40, Idli Sambar 50, Dhokla 40 - steamed, live cart",
    price: 50,
  },
  {
    id: "post-921996420553275441291",
    city: "Mumbai, IN",
    restaurant: "Bhaap Re Bhaap (Versova, Andheri West)",
    reel_url: "https://www.instagram.com/reel/DQLjSXoDBEb/",
    creator_handle: "@bhaaprebhaap",
    protein: "44g",
    fiber: "6g",
    calories: "310",
    sugar: "1g",
    caption_for_app: "0% Oil Steamed Chicken — pure steam-cooked herb chicken with sweet corn & raw salad for gym fuel",
    caption: "0% Oil Steamed Chicken - Bhaap Re Bhaap Versova — Steamed chicken + corn + salad for gym protein",
    views: "430k",
    type: "real",
    dish_name: "0% Oil Steamed Chicken Power Bowl",
    thumbnail: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "zero-oil", "high-protein", "mumbai", "gym-fuel", "steamed"],
    eating_type: "creator tasting succulent 0% oil steamed chicken strips",
    cooking_fat: "0% Oil / Pure Pressure Steam Cooked",
    verified: true,
    why: "Steamed chicken + corn + salad for gym protein",
    why_off_delivery: "Steamed chicken + corn + salad for gym protein (0% oil, Versova)",
    price: 160,
  },
  {
    id: "post-438260157859515064817",
    city: "Mumbai, IN",
    restaurant: "Spoons of Indore Mumbai Cart (Nariman Point)",
    reel_url: "https://www.facebook.com/reel/1744974889871591/",
    creator_handle: "@spoonsofindore",
    protein: "9g",
    fiber: "9g",
    calories: "195",
    sugar: "3g",
    caption_for_app: "Healthy Salad Sandwich — raw cucumber, juicy beetroot, tomato & green herb chutney on fresh soft bread",
    caption: "Healthy Salad Sandwich - Spoons of Indore Mumbai cart — Potato base + cucumber, beetroot, tomato - raw salad sandwich",
    views: "210k",
    type: "real",
    dish_name: "Loaded Raw Garden Salad Sandwich",
    thumbnail: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "raw-veggies", "mumbai-cart", "zero-butter", "budget-healthy"],
    eating_type: "creator eating fresh layered beetroot cucumber sandwich",
    cooking_fat: "Zero Butter / Fresh Mint Coriander Chutney",
    verified: true,
    why: "Potato base + cucumber, beetroot, tomato - raw salad sandwich",
    why_off_delivery: "Potato base + cucumber, beetroot, tomato - raw salad sandwich",
    price: 60,
  },

  // -------------------------------------------------------------
  // 3. Kolkata
  // -------------------------------------------------------------
  {
    id: "post-954170407813247297570",
    city: "Kolkata, IN",
    restaurant: "New Market Huge Kadai Ghugni Stall",
    reel_url: "https://www.instagram.com/reel/DUTImOojFD-/",
    creator_handle: "@kolkatagurban",
    protein: "15g",
    fiber: "13g",
    calories: "185",
    sugar: "2g",
    caption_for_app: "Ghugni Chaat New Market Kolkata — simmering yellow peas, fresh tomato, green chillies & tamarind (Rs 30 bowl)",
    caption: "Ghugni Chaat New Market Kolkata - huge kadai — Yellow peas, tomato, chilli, tamarind - Rs 30 bowl, eaten on footpath",
    views: "520k",
    type: "real",
    dish_name: "Ghugni Chaat & Jhal Muri",
    thumbnail: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "kolkata-heritage", "yellow-peas", "high-fiber", "plant-protein", "footpath-gem"],
    eating_type: "creator eating piping hot yellow pea ghugni from leaf bowl",
    cooking_fat: "Cold-Pressed Mustard Oil (Minimal drop)",
    verified: true,
    why: "Yellow peas, tomato, chilli, tamarind - Rs 30 bowl, eaten on footpath",
    why_off_delivery: "Yellow peas, tomato, chilli, tamarind - Rs 30 bowl, eaten on footpath",
    price: 30,
  },
  {
    id: "post-595358047054526831123",
    city: "Kolkata, IN",
    restaurant: "College Street Heritage Aloo Kabli Wallah",
    reel_url: "https://www.instagram.com/reel/DcLnhPuv8jk/",
    creator_handle: "@kolkataclassics",
    protein: "12g",
    fiber: "10g",
    calories: "165",
    sugar: "1g",
    caption_for_app: "Aloo Kabli Kolkata Classic — boiled potato cubes, soaked black chana & yellow peas tossed with dry roasted bhaja masala (100% oil-free)",
    caption: "Aloo Kabli - Healthy Kolkata Classic — Boiled potato + peas + black chana, bhaja masala, oil-free",
    views: "340k",
    type: "real",
    dish_name: "Oil-Free Aloo Kabli & Black Chana Toss",
    thumbnail: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "oil-free", "black-chana", "bhaja-masala", "kolkata", "gut-friendly"],
    eating_type: "creator eating tangy oil-free chana potato bowl",
    cooking_fat: "100% Oil-Free / Tamarind & Bhaja Masala Toss",
    verified: true,
    why: "Boiled potato + peas + black chana, bhaja masala, oil-free",
    why_off_delivery: "Boiled potato + peas + black chana, bhaja masala, oil-free",
    price: 25,
  },
  {
    id: "post-457384313365363399345",
    city: "Kolkata, IN",
    restaurant: "Dacres Lane & Maidan Live Jhal Muri Artisans",
    reel_url: "https://www.instagram.com/reel/DbHSBcJy_2Z/",
    creator_handle: "@calcutta_street_food",
    protein: "7g",
    fiber: "6g",
    calories: "155",
    sugar: "1g",
    caption_for_app: "Authentic Jhal Muri making — crisp puffed rice, sprouted chana, fresh cucumber, onion & raw mustard oil live tossed in tin can",
    caption: "Jhal Muri making - Kolkata — Puffed rice + sev + onion tomato cucumber live toss",
    views: "710k",
    type: "real",
    dish_name: "Hand-Tossed Artisanal Jhal Muri",
    thumbnail: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "live-tossed", "mustard-oil", "kolkata-icon", "puffed-rice", "soggy-if-delivered"],
    eating_type: "creator eating freshly shaken jhal muri in paper thonga",
    cooking_fat: "Raw Cold-Pressed Mustard Oil (Few Drops)",
    verified: true,
    why: "Puffed rice + sev + onion tomato cucumber live toss",
    why_off_delivery: "Puffed rice + sev + onion tomato cucumber live toss (goes completely soggy in 10 mins)",
    price: 20,
  },

  // -------------------------------------------------------------
  // 4. Chennai
  // -------------------------------------------------------------
  {
    id: "post-101955208576144303503",
    city: "Chennai, IN",
    restaurant: "Mylapore Kabaleeswarar Temple Sundal Kiosk",
    reel_url: "https://www.facebook.com/reel/1009715328274246/",
    creator_handle: "@mylapore_eats",
    protein: "16g",
    fiber: "12g",
    calories: "180",
    sugar: "1g",
    caption_for_app: "Mylapore's Most Crowded Healthy Spot — warm mixed legume sundal served on banana leaf by temple entrance",
    caption: "Mylapore's Most Crowded Healthy Spot - Sundal — Mixed legume sundal on banana leaf, near Kabaleeswarar temple",
    views: "580k",
    type: "real",
    dish_name: "Sundal - Marina Beach Healthy Spot",
    thumbnail: "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "temple-food", "chennai", "banana-leaf", "high-protein", "legume-sundal"],
    eating_type: "creator eating warm sundal on cut banana leaf",
    cooking_fat: "Cold-Pressed Coconut Oil & Fresh Grated Coconut",
    verified: true,
    why: "Mixed legume sundal on banana leaf, near Kabaleeswarar temple",
    why_off_delivery: "Mixed legume sundal on banana leaf, near Kabaleeswarar temple",
    price: 30,
  },
  {
    id: "post-063636865237864145355",
    city: "Chennai, IN",
    restaurant: "Perambur Sundal Service Stall (4th Year)",
    reel_url: "https://www.facebook.com/reel/1642965237164750/",
    creator_handle: "@perambur_sundal",
    protein: "14g",
    fiber: "9g",
    calories: "190",
    sugar: "1g",
    caption_for_app: "Perambur Sundal Service — boiled peanuts with fragrant curry leaves & tart raw mango slices from steaming steel container",
    caption: "Perambur Sundal Service 4th Year — Boiled peanuts + curry leaves + raw mango - steel container stall",
    views: "270k",
    type: "real",
    dish_name: "Steamed Peanut Sundal with Raw Mango",
    thumbnail: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "chennai-street", "boiled-peanuts", "raw-mango", "high-protein"],
    eating_type: "creator scooping freshly tossed hot peanut sundal",
    cooking_fat: "Zero Oil / Boiled in Sea Salt Water",
    verified: true,
    why: "Boiled peanuts + curry leaves + raw mango - steel container stall",
    why_off_delivery: "Boiled peanuts + curry leaves + raw mango - steel container stall",
    price: 25,
  },
  {
    id: "post-533238039903014734674",
    city: "Chennai, IN",
    restaurant: "Iyaerkai Suvai Shop (Women-Run Clean Co-op)",
    reel_url: "https://www.instagram.com/reel/DXUnRimjLGl/",
    creator_handle: "@chennaieatshealthy",
    protein: "17g",
    fiber: "11g",
    calories: "195",
    sugar: "2g",
    caption_for_app: "Chennai Eats Healthy — Women-run Iyaerkai Suvai shop: authentic Masala Kala Chana Sundal (Rs 30) + elaneer tender coconut payasam",
    caption: "Chennai Eats Healthy - Masala Sundal Rs 30 — Women-run Iyaerkai Suvai shop, thattu vada + sundal + elaneer payasam",
    views: "410k",
    type: "real",
    dish_name: "Iyaerkai Suvai Masala Sundal & Herbal Broth",
    thumbnail: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "women-run", "chennai", "masala-sundal", "organic", "clean-oil"],
    eating_type: "creator eating wholesome spiced kala chana sundal",
    cooking_fat: "Cold-Pressed Sesame Oil & Mustard Tempered",
    verified: true,
    why: "Women-run Iyaerkai Suvai shop, thattu vada + sundal + elaneer payasam",
    why_off_delivery: "Women-run Iyaerkai Suvai shop, thattu vada + sundal + elaneer payasam",
    price: 30,
  },

  // -------------------------------------------------------------
  // 5. Bengaluru
  // -------------------------------------------------------------
  {
    id: "post-524815080205153456973",
    city: "Bengaluru, IN",
    restaurant: "Devanahalli Gowdru Oota",
    reel_url: "https://www.facebook.com/reel/1653306666138942/",
    creator_handle: "@devanahalli_gowdru",
    protein: "12g",
    fiber: "15g",
    calories: "270",
    sugar: "0g",
    caption_for_app: "Ragi Mudde Making — traditional paddle-turned finger millet balls served piping hot with herbal dill leaf bassaru (swallowed whole)",
    caption: "Ragi Mudde Making - Devanahalli Gowdru — Traditional method - not to be chewed, eaten whole with saaru",
    views: "620k",
    type: "real",
    dish_name: "Ragi Mudde + Bassaru",
    thumbnail: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "millet-staple", "bengaluru-heritage", "high-fiber", "low-gi", "eaten-hot"],
    eating_type: "creator swallowing bite of ragi mudde with rich bassaru gravy",
    cooking_fat: "Zero Oil / Slow Steamed with Wooden Turning Stick",
    verified: true,
    why: "Traditional method - not to be chewed, eaten whole with saaru",
    why_off_delivery: "Traditional method - not to be chewed, eaten whole with saaru (hardens like rubber if cooled)",
    price: 90,
  },
  {
    id: "post-802153250461298997904",
    city: "Bengaluru, IN",
    restaurant: "Gandhi Nagar 100-Year Mudde Mess",
    reel_url: "https://www.facebook.com/reel/2110964906457346/",
    creator_handle: "@bengaluru_muddemess",
    protein: "16g",
    fiber: "16g",
    calories: "320",
    sugar: "0g",
    caption_for_app: "Mudde Mess Gandhi Nagar (100 years old) — unlimited steaming hot Ragi Mudde with sprouted horsegram saaru (Rs 130)",
    caption: "Mudde Mess Gandhi Nagar - 100 year old — Ragi mudde unlimited Rs 130, mudde hardens if packed",
    views: "890k",
    type: "real",
    dish_name: "100-Year Heritage Mudde & Sprouted Saaru Meal",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "heritage-mess", "100-years", "unlimited", "bengaluru", "superfood"],
    eating_type: "creator enjoying unlimited hot ragi mudde at communal bench",
    cooking_fat: "Zero Added Fat / Herbal Lentil Broth",
    verified: true,
    why: "Ragi mudde unlimited Rs 130, mudde hardens if packed",
    why_off_delivery: "Ragi mudde unlimited Rs 130, mudde hardens if packed (must be eaten straight from pot)",
    price: 130,
  },
  {
    id: "post-338192515151399085303",
    city: "Bengaluru, IN",
    restaurant: "Malleshwaram Morning Mudde Cart Vendor",
    reel_url: "https://www.facebook.com/reel/1568834821438842/",
    creator_handle: "@namma_bengaluru_bites",
    protein: "24g",
    fiber: "13g",
    calories: "320",
    sugar: "0g",
    caption_for_app: "Live Serving of Ragi Mudde — hot finger millet ball with rustic country egg & brown aromatic herbal curry at footpath stall",
    caption: "Ragi Mudde with curry - Vendor at Bengaluru — Live serving of mudde + brown curry + eggs",
    views: "470k",
    type: "real",
    dish_name: "Hot Ragi Mudde with Boiled Country Eggs",
    thumbnail: "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "high-protein", "country-eggs", "millet", "bengaluru-cart"],
    eating_type: "creator eating steaming mudde with boiled country eggs",
    cooking_fat: "Slow-Simmered Spiced Herbal Broth",
    verified: true,
    why: "Live serving of mudde + brown curry + eggs",
    why_off_delivery: "Live serving of mudde + brown curry + eggs (served boiling hot on morning cart)",
    price: 80,
  },

  // -------------------------------------------------------------
  // 6. Hyderabad
  // -------------------------------------------------------------
  {
    id: "post-041644945045367801566",
    city: "Hyderabad, IN",
    restaurant: "Raju Gari Rottelu (BN Reddy Nagar)",
    reel_url: "https://www.facebook.com/reel/1086930994319948/",
    creator_handle: "@rajugari_rottelu",
    protein: "10g",
    fiber: "14g",
    calories: "155",
    sugar: "0g",
    caption_for_app: "Jonna Roti Rs 18 — hand-patted Sorghum (Jowar) and Sajja (Pearl Millet) rotis baked on cast-iron tawa without oil (high fiber, zero gluten)",
    caption: "Jonna Roti Rs 18 - Raju Gari Rottelu BN Reddy — High fibre low fat gluten free - made on tawa, delivery only local",
    views: "610k",
    type: "real",
    dish_name: "Jonna Rotte / Sajja Roti + Protein Salad",
    thumbnail: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "jowar-roti", "millet", "gluten-free", "high-fiber", "hyderabad", "tapped-by-hand"],
    eating_type: "creator eating warm puffy jonna roti with tomato chutney",
    cooking_fat: "Dry Cast Iron Tawa / Zero Oil",
    verified: true,
    why: "High fibre low fat gluten free - made on tawa, delivery only local",
    why_off_delivery: "High fibre low fat gluten free - made on tawa, delivery only local",
    price: 18,
  },
  {
    id: "post-014419386607495636931",
    city: "Hyderabad, IN",
    restaurant: "Alkapur Healthy Protein Cart (IAS Aspirant Vendor)",
    reel_url: "https://www.instagram.com/reel/DU49nCRkY_1/",
    creator_handle: "@alkapur_protein_cart",
    protein: "22g",
    fiber: "14g",
    calories: "220",
    sugar: "2g",
    caption_for_app: "Healthy Protein Salad Rs 25 — Kabuli chana, kala chana, lobia, rajma, sweet corn & live mung sprouts by civil service aspirant",
    caption: "Healthy Protein Salad Rs 25 Alkapur — Kabuli chana, kala chana, lobia, rajma, corn, sprouts - IAS turned vendor",
    views: "780k",
    type: "real",
    dish_name: "Six-Legume Power Protein Salad",
    thumbnail: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "ias-aspirant-vendor", "six-legumes", "high-protein", "hyderabad", "superfood"],
    eating_type: "creator eating colorful multi-bean protein bowl at roadside",
    cooking_fat: "Zero Oil / Fresh Squeezed Lime & Himalayan Salt",
    verified: true,
    why: "Kabuli chana, kala chana, lobia, rajma, corn, sprouts - IAS turned vendor",
    why_off_delivery: "Kabuli chana, kala chana, lobia, rajma, corn, sprouts - IAS turned vendor (Rs 25 fresh bowl)",
    price: 25,
  },
  {
    id: "post-828766107738814204443",
    city: "Hyderabad, IN",
    restaurant: "Ranvi's Morning Health Stall (Kukatpally)",
    reel_url: "https://www.instagram.com/reel/DcVzRvAAqMC/",
    creator_handle: "@ranvis_health_kukatpally",
    protein: "12g",
    fiber: "10g",
    calories: "175",
    sugar: "3g",
    caption_for_app: "Ranvi's Morning Stall (7–11am) — fresh pressed cold coconut milk, warm nourishing ragi java, sprouted salads & millet energy balls",
    caption: "Ranvi's Coconut Milk + Ragi Java - Kukatpally — Morning stall 7-11am, coconut milk + millet laddu + sprouts",
    views: "440k",
    type: "real",
    dish_name: "Cold Coconut Milk, Ragi Java & Sprout Platter",
    thumbnail: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "morning-only", "ragi-java", "coconut-milk", "gut-soothing", "hyderabad"],
    eating_type: "creator sipping fresh coconut milk and warm ragi java",
    cooking_fat: "Raw Cold Coconut / Zero Refined Fat",
    verified: true,
    why: "Morning stall 7-11am, coconut milk + millet laddu + sprouts",
    why_off_delivery: "Morning stall 7-11am, coconut milk + millet laddu + sprouts (only 4 hours a day)",
    price: 40,
  },

  // -------------------------------------------------------------
  // 7. Pune
  // -------------------------------------------------------------
  {
    id: "post-071305045184875255408",
    city: "Pune, IN",
    restaurant: "Durga Tekdi Weekend Diet Chopati (Nigdi)",
    reel_url: "https://www.instagram.com/reel/DWf1TGTk5BN/",
    creator_handle: "@pune_diet_chopati",
    protein: "17g",
    fiber: "13g",
    calories: "235",
    sugar: "3g",
    caption_for_app: "Durga Tekdi Weekend Diet Chopati — multi-sprout chaat, hot jowar-bajra thalipeeth, ABC detox juice & fresh rose apple",
    caption: "Durga Tekdi Diet Chopati - Sprouts Chaat — Weekend only market - sprouts chaat, thalipeeth, ABC juice, rose apple",
    views: "530k",
    type: "real",
    dish_name: "Sprouts Chaat + Thalipeeth - Diet Choppati",
    thumbnail: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "weekend-only", "tekdi-market", "thalipeeth", "pune", "abc-juice", "sprout-chaat"],
    eating_type: "creator eating fresh thalipeeth overlooking morning hills",
    cooking_fat: "Cast Iron Griddled with Pure Cow Ghee drop",
    verified: true,
    why: "Weekend only market - sprouts chaat, thalipeeth, ABC juice, rose apple",
    why_off_delivery: "Weekend only market - sprouts chaat, thalipeeth, ABC juice, rose apple (open 6am-9am weekends only)",
    price: 50,
  },
  {
    id: "post-567867795682173078955",
    city: "Pune, IN",
    restaurant: "Sisters Spoon Salad (FC Road Umbrella Cart)",
    reel_url: "https://www.facebook.com/reel/1050201881235382/",
    creator_handle: "@sistersspoonsalad",
    protein: "15g",
    fiber: "11g",
    calories: "205",
    sugar: "2g",
    caption_for_app: "Sisters Spoon Salad — guilt-free sprouted moong & matki bhel with roasted foxnut (makhana) chaat under street umbrella",
    caption: "Sisters Spoon Salad - Guilt free sprout bhel — Roadside cart under umbrella, sprout bhel + makhana chaat",
    views: "360k",
    type: "real",
    dish_name: "Guilt-Free Sprout Bhel & Roasted Makhana",
    thumbnail: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "pune-street", "guilt-free-bhel", "makhana", "sprouts", "clean-chaat"],
    eating_type: "creator enjoying crunchy sprout bhel with roasted makhana",
    cooking_fat: "Zero Oil / Dry Roasted Makhana & Live Tossed Sprouts",
    verified: true,
    why: "Roadside cart under umbrella, sprout bhel + makhana chaat",
    why_off_delivery: "Roadside cart under umbrella, sprout bhel + makhana chaat",
    price: 60,
  },

  // -------------------------------------------------------------
  // 8. Ahmedabad
  // -------------------------------------------------------------
  {
    id: "post-950083033555297593693",
    city: "Ahmedabad, IN",
    restaurant: "Manali Ben 13-Year Legacy Stall (Paldi)",
    reel_url: "https://www.instagram.com/reel/DZ6wd3oB9OF/",
    creator_handle: "@manaliben_paldi",
    protein: "13g",
    fiber: "9g",
    calories: "185",
    sugar: "1g",
    caption_for_app: "Manali Ben (13 Years in Paldi) — authentic homemade steamed Khichu, Handvo, Muthiya & Dhokla from super hygienic woman-run cart",
    caption: "Manali Ben 13 Years Handvo Khichu Paldi — Homemade dhokla, handvo, muthiya, khichu - super hygienic lady cart",
    views: "570k",
    type: "real",
    dish_name: "Khichu & Handvo - Steamed Gujarati",
    thumbnail: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "gujarati-heritage", "lady-run-cart", "steamed", "ahmedabad", "khichu", "handvo"],
    eating_type: "creator eating piping hot steamed khichu with methi masala",
    cooking_fat: "Cold-Pressed Groundnut Oil & Methi Sambharo",
    verified: true,
    why: "Homemade dhokla, handvo, muthiya, khichu - super hygienic lady cart",
    why_off_delivery: "Homemade dhokla, handvo, muthiya, khichu - super hygienic lady cart",
    price: 40,
  },
  {
    id: "post-313431096222481532807",
    city: "Ahmedabad, IN",
    restaurant: "Aavrish Food Stall (SG Highway Ring Road)",
    reel_url: "https://www.facebook.com/reel/1384148193785214/",
    creator_handle: "@aavrish_foodstall",
    protein: "11g",
    fiber: "8g",
    calories: "190",
    sugar: "1g",
    caption_for_app: "Aavrish Food Stall — Uncle & Aunty preparing sizzling fresh Handvo (Rs 50) and piping hot Khichu (Rs 30) in cast iron kadai",
    caption: "Aavrish Food Stall - Handvo Rs 50 Khichu Rs 30 — Uncle aunty making hot handvo in kadai on ring road",
    views: "390k",
    type: "real",
    dish_name: "Kadai Sizzled Handvo & Steamed Rice Khichu",
    thumbnail: "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "kadai-steamed", "ring-road-gem", "family-run", "gujarat"],
    eating_type: "creator tasting steaming handvo right off the kadai",
    cooking_fat: "Steamed & Kadai Seared with Mustard Seeds",
    verified: true,
    why: "Uncle aunty making hot handvo in kadai on ring road",
    why_off_delivery: "Uncle aunty making hot handvo in kadai on ring road (Rs 50 handvo / Rs 30 khichu)",
    price: 30,
  },
  {
    id: "post-978089993773443624827",
    city: "Ahmedabad, IN",
    restaurant: "Food Eternity Health Kiosk (Navrangpura)",
    reel_url: "https://www.facebook.com/reel/38025622380415557/",
    creator_handle: "@foodeternity_gujarat",
    protein: "15g",
    fiber: "10g",
    calories: "210",
    sugar: "0g",
    caption_for_app: "Healthy High-Protein Khichu (14g Protein) — soy flour + rice flour dough tempered with pure A2 cow ghee & fresh green chillies",
    caption: "Healthy Khichu 14g protein - Food Eternity — Rice flour + soy flour + ghee tempered - high protein version",
    views: "460k",
    type: "real",
    dish_name: "High-Protein Soy & Rice Flour Khichu",
    thumbnail: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "high-protein", "a2-cow-ghee", "soy-boosted", "ahmedabad"],
    eating_type: "creator eating soft savory high-protein warm khichu",
    cooking_fat: "A2 Desi Cow Ghee Tempering",
    verified: true,
    why: "Rice flour + soy flour + ghee tempered - high protein version",
    why_off_delivery: "Rice flour + soy flour + ghee tempered - high protein version",
    price: 50,
  },

  // -------------------------------------------------------------
  // 9. Jaipur
  // -------------------------------------------------------------
  {
    id: "post-096908328877864253600",
    city: "Jaipur, IN",
    restaurant: "Chaudhary Ji Raja Park Kiosk",
    reel_url: "https://www.instagram.com/reel/DQyrO3MjdxB/",
    creator_handle: "@chaudharyji_jaipur",
    protein: "11g",
    fiber: "12g",
    calories: "165",
    sugar: "1g",
    caption_for_app: "Bajra Raabdi at Raja Park — garma garam pearl millet raabdi with roasted khicha papad (winter morning specialty 6am–9am)",
    caption: "Bajra Raabdi - Jaipur Raja Park Chaudhary Ji — Garma garam bajra raabdi + khicha papad - winter only 6-9am",
    views: "670k",
    type: "real",
    dish_name: "Bajra Raabdi - Fermented Probiotic",
    thumbnail: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "rajasthan-heritage", "winter-only", "bajra-raabdi", "jaipur", "probiotic", "khicha-papad"],
    eating_type: "creator drinking piping hot bajra raabdi from kulhad with khicha papad",
    cooking_fat: "Zero Oil / Churned Buttermilk & Pearl Millet Clay Pot Brew",
    verified: true,
    why: "Garma garam bajra raabdi + khicha papad - winter only 6-9am",
    why_off_delivery: "Garma garam bajra raabdi + khicha papad - winter only 6-9am (cannot be delivered, cools in minutes)",
    price: 40,
  },
  {
    id: "post-517859397672356233420",
    city: "Jaipur, IN",
    restaurant: "Heritage Moth Bajre ki Raabdi Artisans",
    reel_url: "https://www.facebook.com/reel/1164505475844299/",
    creator_handle: "@yourfoodlab",
    protein: "14g",
    fiber: "13g",
    calories: "175",
    sugar: "1g",
    caption_for_app: "Moth Bajre ki Raabdi (Your Food Lab) — traditional 8-10 hour slow-fermented buttermilk and moth bean probiotic cooling elixir",
    caption: "Moth Bajre ki Raabdi - Your Food Lab Jaipur story — Fermented 8-10 hrs with buttermilk, anti-heat probiotic drink",
    views: "920k",
    type: "real",
    dish_name: "Slow-Fermented Moth Bajre ki Raabdi Elixir",
    thumbnail: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    tags: ["off-delivery", "fermented", "probiotic", "gut-health", "moth-bean", "bajra", "jaipur-heritage"],
    eating_type: "creator tasting traditional cooling sour fermented raabdi",
    cooking_fat: "100% Oil-Free / Live Cultured Buttermilk Probiotic",
    verified: true,
    why: "Fermented 8-10 hrs with buttermilk, anti-heat probiotic drink",
    why_off_delivery: "Fermented 8-10 hrs with buttermilk, anti-heat probiotic drink (eaten fresh on spot)",
    price: 35,
  },
];
