// lib/mockData.ts

export interface Dish {
  id: string;
  name: string;
  restaurant: string;
  restaurantAddress: string;
  city: string;
  coordinates: {
    lat: number;
    lng: number;
  };
  price: number;
  rating: number;
  reviewsCount: number;
  image: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  dietTags: string[];
  cookingFat: string;
  isSeedOilFree: boolean;
  isGlutenFree: boolean;
  isKeto: boolean;
  isGrassFed: boolean;
  isDairyFree: boolean;
  highlights: string[];
  ingredients: string[];
  chefNotes: string;
  matchScore?: number;
}

export interface CreatorShort {
  id: string;
  creator: string;
  handle: string;
  platform: 'Instagram' | 'TikTok' | 'YouTube';
  thumbnail: string;
  videoUrl: string;
  title: string;
  views: string;
  location?: string;
}

export interface CityLocation {
  name: string;
  state: string;
  lat: number;
  lng: number;
  zoom: number;
}

export const ALL_CITIES_LOCATION: CityLocation = {
  name: 'All Locations',
  state: 'US',
  lat: 39.8283,
  lng: -98.5795,
  zoom: 4,
};

export const CITY_LOCATIONS: CityLocation[] = [
  { name: 'New York City', state: 'NY', lat: 40.7128, lng: -74.006, zoom: 12 },
  { name: 'Miami', state: 'FL', lat: 25.7617, lng: -80.1918, zoom: 13 },
  { name: 'Austin', state: 'TX', lat: 30.2672, lng: -97.7431, zoom: 13 },
  { name: 'Los Angeles', state: 'CA', lat: 34.0522, lng: -118.2437, zoom: 12 },
  { name: 'San Francisco', state: 'CA', lat: 37.7749, lng: -122.4194, zoom: 13 },
  { name: 'Chicago', state: 'IL', lat: 41.8781, lng: -87.6298, zoom: 13 },
  { name: 'Seattle', state: 'WA', lat: 47.6062, lng: -122.3321, zoom: 13 },
  { name: 'Boston', state: 'MA', lat: 42.3601, lng: -71.0589, zoom: 13 },
  { name: 'Denver', state: 'CO', lat: 39.7392, lng: -104.9903, zoom: 13 },
  { name: 'Washington, DC', state: 'DC', lat: 38.9072, lng: -77.0369, zoom: 13 },
];

export const INITIAL_DISHES: Dish[] = [
  // NEW YORK CITY
  {
    id: 'dish-nyc-1',
    name: 'Grass-Fed Beef Meatballs',
    restaurant: 'Hearth',
    restaurantAddress: '403 E 12th St, New York, NY',
    city: 'New York City',
    coordinates: { lat: 40.7298, lng: -73.9816 },
    price: 28.0,
    rating: 4.8,
    reviewsCount: 842,
    image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=800&q=80',
    calories: 520,
    protein: 45,
    carbs: 8,
    fat: 32,
    fiber: 2,
    dietTags: ['Seed Oil Free', 'Grass-Fed', 'Gluten Free'],
    cookingFat: 'Beef Tallow & Organic Butter',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: false,
    isGrassFed: true,
    isDairyFree: false,
    highlights: ['100% Seed Oil Free Kitchen', 'Grass-Fed Beef', 'Milled Organic Tomatoes'],
    ingredients: ['Grass-Fed Ground Beef', 'Organic Tomato Sauce', 'Ricotta', 'Extra Virgin Olive Oil'],
    chefNotes: 'Hearth famously transitioned to a 100% seed-oil-free kitchen, cooking exclusively with butter, tallow, and EVOO.',
  },
  {
    id: 'dish-nyc-2',
    name: '100% Pasture-Raised Rotisserie Half Bird',
    restaurant: 'Springbone Kitchen',
    restaurantAddress: '90 W 3rd St, Greenwich Village, NY',
    city: 'New York City',
    coordinates: { lat: 40.7298, lng: -73.9992 },
    price: 21.0,
    rating: 4.9,
    reviewsCount: 470,
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=800&q=80',
    calories: 540,
    protein: 60,
    carbs: 2,
    fat: 30,
    fiber: 0,
    dietTags: ['Seed Oil Free', 'Pasture-Raised', 'Keto', 'Gluten Free', 'Dairy Free'],
    cookingFat: 'Natural Rendered Chicken Fat & Olive Oil',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: true,
    isGrassFed: false,
    isDairyFree: true,
    highlights: ['Dedicated 100% Seed-Oil-Free Kitchen', 'Certified Pasture-Raised Poultry', 'Zero Cane Sugar or Seed Starches'],
    ingredients: ['Pasture-Raised Rotisserie Chicken (14oz)', 'House Chimichurri (Organic Olive Oil & Herbs)', 'Flaky Sea Salt'],
    chefNotes: 'Cooked in a 100% certified seed-oil-free kitchen. Seasoned purely with sea salt, fresh garlic, and wild herbs.',
  },
  {
    id: 'dish-nyc-3',
    name: 'Steamed Wild Atlantic Black Sea Bass',
    restaurant: 'Le Bernardin',
    restaurantAddress: '155 W 51st St, Midtown Manhattan, NY',
    city: 'New York City',
    coordinates: { lat: 40.7615, lng: -73.9818 },
    price: 74.0,
    rating: 4.9,
    reviewsCount: 790,
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=800&q=80',
    calories: 390,
    protein: 48,
    carbs: 6,
    fat: 18,
    fiber: 2,
    dietTags: ['Seed Oil Free', 'Wild Caught', 'Gluten Free', 'Dairy Free'],
    cookingFat: 'Cold-Pressed Spanish EVOO Emulsion',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: true,
    isGrassFed: false,
    isDairyFree: true,
    highlights: ['3-Michelin Star Sourcing', 'Line-Caught Local Sea Bass', 'Pure Aromatic Infusion'],
    ingredients: ['Line-Caught NY Black Sea Bass (8oz)', 'Baby Bok Choy', 'Ginger-Scallion Emulsion (EVOO)', 'Micro Cilantro'],
    chefNotes: 'Delicately steamed. Dressed in a pristine ginger and scallion emulsion emulsified with single-origin cold-pressed olive oil.',
  },

  // LOS ANGELES
  {
    id: 'dish-la-1',
    name: 'Organic Buffalo Cauliflower (Raw/Vegan)',
    restaurant: 'Cafe Gratitude',
    restaurantAddress: '639 N Larchmont Blvd, Los Angeles, CA',
    city: 'Los Angeles',
    coordinates: { lat: 34.0841, lng: -118.3241 },
    price: 18.0,
    rating: 4.7,
    reviewsCount: 1205,
    image: 'https://images.unsplash.com/photo-1621689240409-77f6b98696eb?auto=format&fit=crop&w=800&q=80',
    calories: 310,
    protein: 8,
    carbs: 22,
    fat: 20,
    fiber: 8,
    dietTags: ['Vegan', 'Gluten Free', 'Clean Eats'],
    cookingFat: 'Cold-Pressed Olive Oil / Baked',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: false,
    isGrassFed: false,
    isDairyFree: true,
    highlights: ['100% Organic', 'Plant-Based', 'Soy Free'],
    ingredients: ['Organic Cauliflower', 'Cashew Aioli', 'Cold-Pressed Olive Oil', 'Cayenne'],
    chefNotes: 'Baked rather than fried, keeping the lipid profile clean while maximizing crunch and flavor.',
  },

  // SAN FRANCISCO
  {
    id: 'dish-sf-1',
    name: "General Tso's Chicken (Paleo)",
    restaurant: 'Kitava',
    restaurantAddress: '2011 Mission St, San Francisco, CA',
    city: 'San Francisco',
    coordinates: { lat: 37.765, lng: -122.4197 },
    price: 22.0,
    rating: 4.9,
    reviewsCount: 650,
    image: 'https://images.unsplash.com/photo-1525159691880-928d3bd7147a?auto=format&fit=crop&w=800&q=80',
    calories: 480,
    protein: 42,
    carbs: 15,
    fat: 26,
    fiber: 4,
    dietTags: ['Seed Oil Free', 'Gluten Free', 'Paleo'],
    cookingFat: 'Avocado Oil',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: false,
    isGrassFed: false,
    isDairyFree: true,
    highlights: ['100% Seed Oil Free Kitchen', 'Refined Sugar Free', 'Cassava Flour Breaded'],
    ingredients: ['Pasture-Raised Chicken', 'Cassava Flour', 'Avocado Oil', 'Coconut Aminos'],
    chefNotes: 'Kitava operates a strict zero seed oil policy. Their frying is done exclusively in 100% avocado oil.',
  },

  // AUSTIN
  {
    id: 'dish-atx-1',
    name: 'Harvest Hash with Grass-Fed Bone Broth',
    restaurant: 'Picnik',
    restaurantAddress: '4801 Burnet Rd, Austin, TX',
    city: 'Austin',
    coordinates: { lat: 30.3188, lng: -97.739 },
    price: 24.0,
    rating: 4.8,
    reviewsCount: 932,
    image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80',
    calories: 410,
    protein: 34,
    carbs: 28,
    fat: 22,
    fiber: 6,
    dietTags: ['Seed Oil Free', 'Gluten Free', 'Grass-Fed'],
    cookingFat: 'Avocado Oil & Ghee',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: false,
    isGrassFed: true,
    isDairyFree: false,
    highlights: ['Peanut-Free Facility', 'Refined Sugar Free', 'Pasture-Raised'],
    ingredients: ['Grass-Fed Beef Sausage', 'Sweet Potatoes', 'Kale', 'Grass-Fed Ghee'],
    chefNotes: 'Picnik is the gold standard for clean eating in Austin, strictly banning peanut, refined sugar, and all industrial seed oils.',
  },

  // CHICAGO
  {
    id: 'dish-chi-1',
    name: 'Wild Caught Salmon Bowl',
    restaurant: 'FARE',
    restaurantAddress: '205 W Wacker Dr, Chicago, IL',
    city: 'Chicago',
    coordinates: { lat: 41.8864, lng: -87.6346 },
    price: 19.5,
    rating: 4.7,
    reviewsCount: 415,
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80',
    calories: 520,
    protein: 38,
    carbs: 45,
    fat: 24,
    fiber: 8,
    dietTags: ['Gluten Free', 'Dairy Free', 'Wild Caught'],
    cookingFat: 'Extra Virgin Olive Oil',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: false,
    isGrassFed: false,
    isDairyFree: true,
    highlights: ['Sustainably Sourced', 'Clean Marinades', 'Vegetable-Forward'],
    ingredients: ['Wild Alaskan Salmon', 'Quinoa', 'Roasted Seasonal Veg', 'EVOO Vinaigrette'],
    chefNotes: 'All bowls at FARE are built around unrefined ingredients with clean fats and zero processed additives.',
  },

  // MIAMI
  {
    id: 'dish-mia-1',
    name: 'Wood-Fired Grass-Fed Ribeye',
    restaurant: 'Los Fuegos by Francis Mallmann',
    restaurantAddress: '3201 Collins Ave, Miami Beach, FL',
    city: 'Miami',
    coordinates: { lat: 25.8075, lng: -80.1236 },
    price: 65.0,
    rating: 4.9,
    reviewsCount: 312,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    calories: 680,
    protein: 58,
    carbs: 0,
    fat: 50,
    fiber: 0,
    dietTags: ['Seed Oil Free', 'Grass-Fed', 'Keto', 'Gluten Free'],
    cookingFat: 'Wood Fire & Beef Tallow',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: true,
    isGrassFed: true,
    isDairyFree: true,
    highlights: ['100% Grass-Fed', 'Open-Fire Cooking', 'Zero Vegetable Oils'],
    ingredients: ['Grass-Fed Ribeye (12oz)', 'Coarse Patagonian Sea Salt', 'Fresh Chimichurri (EVOO based)'],
    chefNotes: 'Cooked traditionally over an open wood fire. Basted in natural rendered tallow. Chimichurri is made in-house daily with pure olive oil.',
  },
  {
    id: 'dish-mia-2',
    name: 'Wild Yellowtail Sashimi & Citrus',
    restaurant: 'Makoto',
    restaurantAddress: '9700 Collins Ave, Bal Harbour, FL',
    city: 'Miami',
    coordinates: { lat: 25.8885, lng: -80.1251 },
    price: 28.0,
    rating: 4.8,
    reviewsCount: 245,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
    calories: 320,
    protein: 42,
    carbs: 4,
    fat: 14,
    fiber: 1,
    dietTags: ['Seed Oil Free', 'Wild Caught', 'Keto', 'Dairy Free'],
    cookingFat: 'Raw / EVOO Drizzle',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: true,
    isGrassFed: false,
    isDairyFree: true,
    highlights: ['Wild Caught', 'High Omega-3s', 'Soy-Free Preparation'],
    ingredients: ['Wild Japanese Yellowtail (8oz)', 'Yuzu Juice', 'Cold-Pressed Extra Virgin Olive Oil', 'Micro Cilantro'],
    chefNotes: 'Served entirely raw. Dressed simply with yuzu and premium olive oil instead of standard seed-oil-laden ponzu.',
  },
  {
    id: 'dish-mia-7',
    name: 'Vegan Superfood Salad',
    restaurant: 'Pura Vida',
    restaurantAddress: '110 Washington Ave, Miami Beach, FL',
    city: 'Miami',
    coordinates: { lat: 25.7702, lng: -80.1347 },
    price: 17.0,
    rating: 4.6,
    reviewsCount: 1540,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    calories: 380,
    protein: 14,
    carbs: 35,
    fat: 22,
    fiber: 12,
    dietTags: ['Vegan', 'Gluten Free', 'Clean Eats'],
    cookingFat: 'Raw / EVOO Dressing',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: false,
    isGrassFed: false,
    isDairyFree: true,
    highlights: ['Locally Sourced Greens', 'Antioxidant Rich', 'House-made Dressing'],
    ingredients: ['Organic Kale', 'Avocado', 'Hemp Seeds', 'Lemon Olive Oil Vinaigrette'],
    chefNotes: 'Dressings are crafted daily in-house avoiding all generic canola and soybean bases.',
  },
  {
    id: 'dish-mia-8',
    name: 'Wild Gulf Red Snapper Ceviche Clásico',
    restaurant: 'CVI.CHE 105',
    restaurantAddress: '105 NE 3rd Ave, Downtown Miami, FL',
    city: 'Miami',
    coordinates: { lat: 25.7766, lng: -80.1906 },
    price: 26.0,
    rating: 4.9,
    reviewsCount: 610,
    image: 'https://images.unsplash.com/photo-1535400255456-984241443b29?auto=format&fit=crop&w=800&q=80',
    calories: 260,
    protein: 36,
    carbs: 8,
    fat: 4,
    fiber: 1,
    dietTags: ['Seed Oil Free', 'Wild Caught', 'Gluten Free', 'Dairy Free'],
    cookingFat: 'Raw Citrus Cure (Zero Added Oil)',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: true,
    isGrassFed: false,
    isDairyFree: true,
    highlights: ['Day-Boat Wild Red Snapper', 'Fresh-Squeezed Lime Leche de Tigre', 'Zero Preservatives'],
    ingredients: ['Wild Gulf Red Snapper (7oz)', 'Fresh Key Lime Juice', 'Aji Limo Peppers', 'Red Onion', 'Cilantro', 'Sea Salt'],
    chefNotes: 'Prepared completely raw with instantaneous citrus cure. Absolutely zero vegetable oils, processed thickeners, or added sugars.',
  },

  // SEATTLE
  {
    id: 'dish-sea-1',
    name: 'Healing Kitchari Bowl (Vegan/GF)',
    restaurant: 'Heartbeet Organic Superfoods Cafe',
    restaurantAddress: '1615 Queen Anne Ave N, Seattle, WA',
    city: 'Seattle',
    coordinates: { lat: 47.6334, lng: -122.3571 },
    price: 16.5,
    rating: 4.8,
    reviewsCount: 388,
    image: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80',
    calories: 410,
    protein: 16,
    carbs: 65,
    fat: 10,
    fiber: 14,
    dietTags: ['Vegan', 'Gluten Free', 'Clean Eats'],
    cookingFat: 'Coconut Oil',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: false,
    isGrassFed: false,
    isDairyFree: true,
    highlights: ['Ayurvedic Spices', '100% Organic', 'Gut-Healing'],
    ingredients: ['Mung Beans', 'Basmati Rice', 'Turmeric', 'Organic Coconut Oil'],
    chefNotes: 'Rooted in Ayurvedic tradition, cooked entirely without refined seed oils using coconut fat for nutrient absorption.',
  },

  // BOSTON
  {
    id: 'dish-bos-1',
    name: 'Raw Pad Thai (Vegan)',
    restaurant: 'Cocobeet',
    restaurantAddress: '100 City Hall Plaza, Boston, MA',
    city: 'Boston',
    coordinates: { lat: 42.361, lng: -71.0583 },
    price: 15.0,
    rating: 4.7,
    reviewsCount: 490,
    image: 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=800&q=80',
    calories: 340,
    protein: 12,
    carbs: 28,
    fat: 18,
    fiber: 9,
    dietTags: ['Vegan', 'Raw', 'Gluten Free', 'Seed Oil Free'],
    cookingFat: 'Raw (Almond/Sesame Base)',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: false,
    isGrassFed: false,
    isDairyFree: true,
    highlights: ['Unprocessed', 'Raw Plant Energy', 'Almond-Based Sauce'],
    ingredients: ['Kelp Noodles', 'Zucchini Ribbons', 'Red Cabbage', 'Raw Almond Butter Dressing'],
    chefNotes: '100% raw vegan dish. The rich texture comes completely from whole nuts and seeds rather than processed oils.',
  },

  // DENVER
  {
    id: 'dish-den-1',
    name: 'Paleo "Meatzza" with Bison',
    restaurant: 'Just BE Kitchen',
    restaurantAddress: '2364 15th St, Denver, CO',
    city: 'Denver',
    coordinates: { lat: 39.7571, lng: -105.0084 },
    price: 24.5,
    rating: 4.9,
    reviewsCount: 1102,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80',
    calories: 680,
    protein: 55,
    carbs: 12,
    fat: 42,
    fiber: 4,
    dietTags: ['Seed Oil Free', 'Gluten Free', 'Keto', 'Grass-Fed'],
    cookingFat: 'Beef Tallow',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: true,
    isGrassFed: true,
    isDairyFree: true,
    highlights: ['Grain-Free Crust', 'Local Colorado Bison', 'Zero Processed Ingredients'],
    ingredients: ['Almond Flour Crust', 'Ground Bison', 'House Tomato Sauce', 'Olive Oil'],
    chefNotes: 'Just BE Kitchen is explicitly 100% gluten, grain, and refined sugar free, utilizing only tallow, olive, and coconut oils.',
  },

  // WASHINGTON, DC
  {
    id: 'dish-dc-1',
    name: 'Roasted Salmon Bowl (GF)',
    restaurant: 'The Little Beet',
    restaurantAddress: '1212 18th St NW, Washington, DC',
    city: 'Washington, DC',
    coordinates: { lat: 38.9056, lng: -77.0417 },
    price: 18.0,
    rating: 4.6,
    reviewsCount: 775,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    calories: 490,
    protein: 36,
    carbs: 38,
    fat: 22,
    fiber: 7,
    dietTags: ['Gluten Free', 'Clean Eats'],
    cookingFat: 'Olive Oil Blend',
    isSeedOilFree: false,
    isGlutenFree: true,
    isKeto: false,
    isGrassFed: false,
    isDairyFree: true,
    highlights: ['100% Gluten Free Facility', 'Nutrient Dense', 'Customizable'],
    ingredients: ['Roasted Salmon', 'Brown Rice', 'Charred Broccoli', 'Avocado Bean Dip'],
    chefNotes: 'A dedicated gluten-free kitchen ensuring zero cross-contamination, focusing on whole, unprocessed vegetables and proteins.',
  },
  {
    id: 'dish-dc-2',
    name: 'Grass-Fed Lamb Platter',
    restaurant: 'Green Almond Pantry',
    restaurantAddress: '3210 Grace St NW, Washington, DC',
    city: 'Washington, DC',
    coordinates: { lat: 38.9042, lng: -77.0621 },
    price: 26.0,
    rating: 4.8,
    reviewsCount: 215,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
    calories: 610,
    protein: 48,
    carbs: 15,
    fat: 38,
    fiber: 5,
    dietTags: ['Seed Oil Free', 'Grass-Fed', 'Gluten Free'],
    cookingFat: 'Extra Virgin Olive Oil',
    isSeedOilFree: true,
    isGlutenFree: true,
    isKeto: true,
    isGrassFed: true,
    isDairyFree: false,
    highlights: ['Mediterranean Prep', 'High Quality Fats', 'Locally Sourced'],
    ingredients: ['Grass-Fed Lamb', 'Braised Greens', 'Cold-Pressed Olive Oil', 'Tzatziki'],
    chefNotes: 'Mediterranean fundamentals done right—cooked almost exclusively with high-quality olive oil and natural animal fats.',
  },
];

export const CREATOR_SHORTS: CreatorShort[] = [
  {
    id: 'short-1',
    creator: 'Elena Rostova',
    handle: '@elenafuel',
    platform: 'Instagram',
    thumbnail: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/reel-1.mp4',
    title: 'Top 3 Seed-Oil-Free Steakhouses in Miami Beach 🔥🥩',
    views: '142.8K',
    location: 'Miami Beach, FL',
  },
  {
    id: 'short-2',
    creator: 'Dr. Marcus Vance',
    handle: '@ancestraldoc',
    platform: 'TikTok',
    thumbnail: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/reel-2.mp4',
    title: 'How to order 100% seed-oil-free sushi in Bal Harbour 🍣✨',
    views: '98.4K',
    location: 'Bal Harbour, FL',
  },
  {
    id: 'short-3',
    creator: 'Chloe Bennett',
    handle: '@chloemiami_eats',
    platform: 'Instagram',
    thumbnail: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/reel-3.mp4',
    title: 'Pasture-raised clean dining crawl in Miami Design District 🌿',
    views: '230.1K',
    location: 'Design District, FL',
  },
  {
    id: 'short-4',
    creator: 'Leo Chen',
    handle: '@leofit_eats',
    platform: 'YouTube',
    thumbnail: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80',
    videoUrl: '/videos/reel-4.mp4',
    title: 'Testing 24-Hour Collagen Bone Broth in Wynwood 🥣⚡️',
    views: '64.9K',
    location: 'Wynwood, FL',
  },
];
