import { INDIA_CURATED_REELS } from './indiaReelsData';

export type ReelCity =
  | "Austin, TX"
  | "New York, NY"
  | "Los Angeles, CA"
  | "San Francisco, CA"
  | "Miami, FL"
  | "Chicago, IL"
  | "Denver, CO"
  | "Seattle, WA"
  | "San Diego, CA"
  | "Nashville, TN"
  | "Washington, DC"
  | "Boston, MA"
  | "Dallas, TX"
  | "Houston, TX"
  | "Atlanta, GA"
  | "Portland, OR"
  | "Phoenix, AZ"
  | "Philadelphia, PA"
  | "Detroit, MI"
  | "Minneapolis, MN"
  | "Charlotte, NC"
  | "Tampa, FL"
  | "Orlando, FL"
  | "Las Vegas, NV"
  | "Sacramento, CA"
  | "Portland, ME"
  | "Delhi, IN"
  | "Ghaziabad, IN"
  | "Noida, IN"
  | "Gurugram, IN"
  | "Mumbai, IN"
  | "Bengaluru, IN"
  | "Kolkata, IN"
  | "Chennai, IN"
  | "Hyderabad, IN"
  | "Pune, IN"
  | "Ahmedabad, IN"
  | "Jaipur, IN"
  | (string & {});

export type ReelType = "real" | "fallback-nationwide" | "scout-card";

export type CookingFat =
  | "Beef Tallow"
  | "Cold-Pressed EVOO"
  | "Grass-Fed Ghee"
  | "Avocado Oil"
  | "Bone Marrow"
  | "Zero Acre";

export interface Reel {
  id: string;
  city: ReelCity | string;
  restaurant: string;
  reel_url: string;
  creator_handle: string;
  protein: string;
  fiber: string;
  calories: string;
  sugar: string;
  caption?: string;
  caption_for_app: string;
  views: string;
  type: ReelType;
  tags?: string[];
  eating_type?: string;
  cooking_fat?: CookingFat | string;
  dish_name?: string;
  thumbnail?: string;
  verified?: boolean;
  macros_text?: string;
  why?: string;
  why_off_delivery?: string;
  price?: number;
}

export const ALL_26_CITIES: ReelCity[] = [
  "Austin, TX",
  "New York, NY",
  "Los Angeles, CA",
  "San Francisco, CA",
  "Miami, FL",
  "Chicago, IL",
  "Denver, CO",
  "Seattle, WA",
  "San Diego, CA",
  "Nashville, TN",
  "Washington, DC",
  "Boston, MA",
  "Dallas, TX",
  "Houston, TX",
  "Atlanta, GA",
  "Portland, OR",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "Detroit, MI",
  "Minneapolis, MN",
  "Charlotte, NC",
  "Tampa, FL",
  "Orlando, FL",
  "Las Vegas, NV",
  "Sacramento, CA",
  "Portland, ME",
];

export const CITIES_LIST: { id: ReelCity; name: string; state: string }[] = [
  { id: "Austin, TX", name: "Austin", state: "TX" },
  { id: "New York, NY", name: "New York", state: "NY" },
  { id: "Los Angeles, CA", name: "Los Angeles", state: "CA" },
  { id: "San Francisco, CA", name: "San Francisco", state: "CA" },
  { id: "Miami, FL", name: "Miami", state: "FL" },
  { id: "Chicago, IL", name: "Chicago", state: "IL" },
  { id: "Denver, CO", name: "Denver", state: "CO" },
  { id: "Seattle, WA", name: "Seattle", state: "WA" },
  { id: "San Diego, CA", name: "San Diego", state: "CA" },
  { id: "Nashville, TN", name: "Nashville", state: "TN" },
  { id: "Washington, DC", name: "Washington", state: "DC" },
  { id: "Boston, MA", name: "Boston", state: "MA" },
  { id: "Dallas, TX", name: "Dallas", state: "TX" },
  { id: "Houston, TX", name: "Houston", state: "TX" },
  { id: "Atlanta, GA", name: "Atlanta", state: "GA" },
  { id: "Portland, OR", name: "Portland", state: "OR" },
  { id: "Phoenix, AZ", name: "Phoenix", state: "AZ" },
  { id: "Philadelphia, PA", name: "Philadelphia", state: "PA" },
  { id: "Detroit, MI", name: "Detroit", state: "MI" },
  { id: "Minneapolis, MN", name: "Minneapolis", state: "MN" },
  { id: "Charlotte, NC", name: "Charlotte", state: "NC" },
  { id: "Tampa, FL", name: "Tampa", state: "FL" },
  { id: "Orlando, FL", name: "Orlando", state: "FL" },
  { id: "Las Vegas, NV", name: "Las Vegas", state: "NV" },
  { id: "Sacramento, CA", name: "Sacramento", state: "CA" },
  { id: "Portland, ME", name: "Portland ME", state: "ME" },
];

export const REELS_DATA: Reel[] = [
  // CURATED INDIAN OFF-DELIVERY REELS
  ...INDIA_CURATED_REELS,
  // REAL REELS (Provided Curated Set)
  {
    id: "ny1",
    city: "New York, NY",
    restaurant: "Matter Formula",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "77g protein bowl — meatballs + chicken + rice + beans + avocado — protein maxing — eating outside",
    caption: "77g protein bowl — meatballs + chicken + rice + beans + avocado — protein maxing — eating outside",
    views: "6.2k",
    type: "real",
    dish_name: "77g Super Protein Bowl",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    tags: ["high-protein", "high-fiber", "clean-fuel"],
    eating_type: "creator eating outside at table",
    verified: true,
  },
  {
    id: "ny2",
    city: "New York, NY",
    restaurant: "The Protein Shop",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Caesar wrap 77g 650cal, Power plate 60g, froyo 50g — macro friendly — eating at table",
    caption: "Caesar wrap 77g 650cal, Power plate 60g, froyo 50g — macro friendly — eating at table",
    views: "8.9k",
    type: "real",
    dish_name: "Grilled Chicken Caesar Wrap",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    tags: ["high-protein", "low-sugar", "macro-friendly"],
    eating_type: "creator eating wrap at dining table",
    verified: true,
  },
  {
    id: "ny3",
    city: "New York, NY",
    restaurant: "Fuel Fever",
    reel_url: "https://www.instagram.com/reel/DcBz7v9xKWD/",
    creator_handle: "@fuelfeverbk",
    protein: "52g",
    fiber: "10g",
    calories: "590",
    sugar: "4g",
    caption_for_app: "Fuel Diesel — bison + chicken + air-baked fries — low sodium clean — eating outside",
    caption: "Fuel Diesel — bison + chicken + air-baked fries — low sodium clean — eating outside",
    views: "4.1k",
    type: "real",
    dish_name: "Fuel Diesel Bison & Chicken Plate",
    thumbnail: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    tags: ["high-protein", "high-fiber", "low-sodium"],
    eating_type: "creator eating outside patio",
    verified: true,
  },
  {
    id: "la1",
    city: "Los Angeles, CA",
    restaurant: "Sweetfin Poke",
    reel_url: "https://www.instagram.com/reel/Dbd3FUkIupe/",
    creator_handle: "@sweetfin",
    protein: "54g",
    fiber: "9g",
    calories: "520",
    sugar: "5g",
    caption_for_app: "HIGH PROTEIN LUNCH 54g Spicy Chicken — gluten free",
    caption: "HIGH PROTEIN LUNCH 54g Spicy Chicken — gluten free",
    views: "7.3k",
    type: "real",
    dish_name: "Spicy Chicken Protein Poke Bowl",
    thumbnail: "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?auto=format&fit=crop&w=800&q=80",
    tags: ["high-protein", "gluten-free", "low-sugar"],
    eating_type: "creator eating poke bowl in sunny LA",
    verified: true,
  },
  {
    id: "la2",
    city: "Los Angeles, CA",
    restaurant: "Health Nut",
    reel_url: "https://www.instagram.com/p/DOWYY-Aj13-/",
    creator_handle: "@healthnutla",
    protein: "56g",
    fiber: "11g",
    calories: "549",
    sugar: "3g",
    caption_for_app: "Protein Packed Low Carb Cobb 56g 549 cal — hand holding bowl",
    caption: "Protein Packed Low Carb Cobb 56g 549 cal — hand holding bowl",
    views: "5.6k",
    type: "real",
    dish_name: "Low Carb Protein Cobb Bowl",
    thumbnail: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    tags: ["high-protein", "high-fiber", "low-sugar", "keto-friendly"],
    eating_type: "creator hand holding bowl at table",
    verified: true,
  },
  {
    id: "aus1",
    city: "Austin, TX",
    restaurant: "Oria",
    reel_url: "https://www.instagram.com/reel/DalxwZPD1DP/",
    creator_handle: "@austinfoodheads",
    protein: "42g",
    fiber: "10g",
    calories: "560",
    sugar: "6g",
    caption_for_app: "Wood-fired Mediterranean high protein bowl — eating at table",
    caption: "Wood-fired Mediterranean high protein bowl — eating at table",
    views: "8.9k",
    type: "real",
    dish_name: "Wood-Fired Mediterranean Bowl",
    thumbnail: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    tags: ["high-protein", "high-fiber", "mediterranean"],
    eating_type: "creator eating at restaurant table",
    verified: true,
  },
  {
    id: "aus2",
    city: "Austin, TX",
    restaurant: "The Well",
    reel_url: "https://www.instagram.com/reel/DW6tHeyjpPh/",
    creator_handle: "@eatwellatx",
    protein: "45g",
    fiber: "12g",
    calories: "520",
    sugar: "5g",
    caption_for_app: "Blueprint future dining — organic clean bowl 45g",
    caption: "Blueprint future dining — organic clean bowl 45g",
    views: "12.3k",
    type: "real",
    dish_name: "Organic Wellness Harvest Bowl",
    thumbnail: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=800&q=80",
    tags: ["high-protein", "high-fiber", "organic", "zero-seed-oils"],
    eating_type: "creator taking first bite on camera",
    verified: true,
  },
  {
    id: "aus3",
    city: "Austin, TX",
    restaurant: "Radius Butcher",
    reel_url: "https://www.instagram.com/reel/DZZFexhOU61/",
    creator_handle: "@radiusbutcher",
    protein: "50g",
    fiber: "9g",
    calories: "590",
    sugar: "4g",
    caption_for_app: "Healthiest grocery in America — high protein bowl",
    caption: "Healthiest grocery in America — high protein bowl",
    views: "21.5k",
    type: "real",
    dish_name: "Butcher Cut Protein Steak Bowl",
    thumbnail: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    tags: ["high-protein", "pasture-raised", "clean-eats"],
    eating_type: "creator eating steak bowl inside butcher shop",
    verified: true,
  },
  {
    id: "den1",
    city: "Denver, CO",
    restaurant: "Just BE Kitchen",
    reel_url: "https://www.instagram.com/p/DcCW_wuGKbT/",
    creator_handle: "@justbekitchen",
    protein: "44g",
    fiber: "11g",
    calories: "540",
    sugar: "5g",
    caption_for_app: "America's first gluten-free fast casual 44g protein",
    caption: "America's first gluten-free fast casual 44g protein",
    views: "6.7k",
    type: "real",
    dish_name: "Gluten-Free Paleo Protein Skillet",
    thumbnail: "https://images.unsplash.com/photo-1514944298352-82d603a11b7e?auto=format&fit=crop&w=800&q=80",
    tags: ["gluten-free", "high-protein", "paleo"],
    eating_type: "creator testing gluten-free skillet dish",
    verified: true,
  },
  {
    id: "chi1",
    city: "Chicago, IL",
    restaurant: "Fare Kitchen",
    reel_url: "https://www.instagram.com/reel/DQZkj-ajoq1/",
    creator_handle: "@farekitchen",
    protein: "42g",
    fiber: "12g",
    calories: "530",
    sugar: "4g",
    caption_for_app: "High fiber low sugar bowl — nutrition coach eating",
    caption: "High fiber low sugar bowl — nutrition coach eating",
    views: "3.1k",
    type: "real",
    dish_name: "Clean Macro Warm Bowl",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    tags: ["high-fiber", "high-protein", "low-sugar"],
    eating_type: "nutrition coach eating on camera",
    verified: true,
  },
  {
    id: "mia1",
    city: "Miami, FL",
    restaurant: "Pat & Phil",
    reel_url: "https://www.instagram.com/reel/DcOeXPCzUFB/",
    creator_handle: "@patandphil_doral",
    protein: "38g",
    fiber: "10g",
    calories: "540",
    sugar: "6g",
    caption_for_app: "Miami's healthiest lunch under $25 38g protein",
    caption: "Miami's healthiest lunch under $25 38g protein",
    views: "8.9k",
    type: "real",
    dish_name: "Signature Clean Protein Plate",
    thumbnail: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    tags: ["high-protein", "high-fiber", "clean-eats"],
    eating_type: "creator enjoying lunch in Miami sunshine",
    verified: true,
  },
  {
    id: "sea1",
    city: "Seattle, WA",
    restaurant: "Sano",
    reel_url: "https://www.instagram.com/reel/DcjmAWbh9bu/",
    creator_handle: "@sano_kirkland",
    protein: "41g",
    fiber: "13g",
    calories: "510",
    sugar: "4g",
    caption_for_app: "FOOD YOU CAN TRUST Organic clean bowl 41g",
    caption: "FOOD YOU CAN TRUST Organic clean bowl 41g",
    views: "2.9k",
    type: "real",
    dish_name: "Trust Kitchen Pacific Salmon Bowl",
    thumbnail: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=800&q=80",
    tags: ["wild-salmon", "high-fiber", "high-protein"],
    eating_type: "creator dining at cafe counter",
    verified: true,
  },
  {
    id: "sd1",
    city: "San Diego, CA",
    restaurant: "Farm To Smash",
    reel_url: "https://www.facebook.com/reel/2068813210393247/",
    creator_handle: "@farmtosmash",
    protein: "48g",
    fiber: "9g",
    calories: "560",
    sugar: "5g",
    caption_for_app: "100% clean smash burgers mukbang high protein",
    caption: "100% clean smash burgers mukbang high protein",
    views: "9.8k",
    type: "real",
    dish_name: "Grass-Fed Clean Smash Burger",
    thumbnail: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
    tags: ["high-protein", "zero-seed-oils", "grass-fed"],
    eating_type: "creator mukbang eating smash burger",
    verified: true,
  },
  {
    id: "dc1",
    city: "Washington, DC",
    restaurant: "AMA",
    reel_url: "https://www.instagram.com/reel/DWeIp-DkceG/",
    creator_handle: "@morganstuphealth",
    protein: "42g",
    fiber: "12g",
    calories: "520",
    sugar: "5g",
    caption_for_app: "The HEALTHIEST Restaurant in America 42g bowl",
    caption: "The HEALTHIEST Restaurant in America 42g bowl",
    views: "6.1k",
    type: "real",
    dish_name: "AMA Superfood Power Bowl",
    thumbnail: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    tags: ["high-protein", "high-fiber", "clean-fuel"],
    eating_type: "creator tasting dish inside restaurant",
    verified: true,
  },

  // FALLBACK NATIONWIDE & SCOUT CARDS FOR EXPANSION CITIES
  // San Francisco, CA
  {
    id: "fb_sanfranciscoca_0",
    city: "San Francisco, CA",
    restaurant: "Matter Formula (Nationwide Viral — Request in San Francisco, CA)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout San Francisco, CA — Comment SOS San Francisco, CA",
    caption: "Nationwide viral 77g protein bowl — Be first to scout San Francisco, CA — Comment SOS San Francisco, CA",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_sanfranciscoca_1",
    city: "San Francisco, CA",
    restaurant: "The Protein Shop (Nationwide Viral — Request in San Francisco, CA)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout San Francisco, CA — Comment SOS San Francisco, CA",
    caption: "Nationwide viral 77g protein bowl — Be first to scout San Francisco, CA — Comment SOS San Francisco, CA",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_sanfranciscoca",
    city: "San Francisco, CA",
    restaurant: "Be first to scout San Francisco, CA",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in San Francisco, CA — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS San Francisco, CA",
    caption: "No clean high-protein reels yet in San Francisco, CA — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS San Francisco, CA",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Nashville, TN
  {
    id: "fb_nashvilletn_0",
    city: "Nashville, TN",
    restaurant: "Matter Formula (Nationwide Viral — Request in Nashville, TN)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Nashville, TN — Comment SOS Nashville, TN",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Nashville, TN — Comment SOS Nashville, TN",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_nashvilletn_1",
    city: "Nashville, TN",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Nashville, TN)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Nashville, TN — Comment SOS Nashville, TN",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Nashville, TN — Comment SOS Nashville, TN",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_nashvilletn",
    city: "Nashville, TN",
    restaurant: "Be first to scout Nashville, TN",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Nashville, TN — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Nashville, TN",
    caption: "No clean high-protein reels yet in Nashville, TN — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Nashville, TN",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Boston, MA
  {
    id: "fb_bostonma_0",
    city: "Boston, MA",
    restaurant: "Matter Formula (Nationwide Viral — Request in Boston, MA)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Boston, MA — Comment SOS Boston, MA",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Boston, MA — Comment SOS Boston, MA",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_bostonma_1",
    city: "Boston, MA",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Boston, MA)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Boston, MA — Comment SOS Boston, MA",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Boston, MA — Comment SOS Boston, MA",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_bostonma",
    city: "Boston, MA",
    restaurant: "Be first to scout Boston, MA",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Boston, MA — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Boston, MA",
    caption: "No clean high-protein reels yet in Boston, MA — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Boston, MA",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Dallas, TX
  {
    id: "fb_dallastx_0",
    city: "Dallas, TX",
    restaurant: "Matter Formula (Nationwide Viral — Request in Dallas, TX)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Dallas, TX — Comment SOS Dallas, TX",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Dallas, TX — Comment SOS Dallas, TX",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_dallastx_1",
    city: "Dallas, TX",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Dallas, TX)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Dallas, TX — Comment SOS Dallas, TX",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Dallas, TX — Comment SOS Dallas, TX",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_dallastx",
    city: "Dallas, TX",
    restaurant: "Be first to scout Dallas, TX",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Dallas, TX — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Dallas, TX",
    caption: "No clean high-protein reels yet in Dallas, TX — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Dallas, TX",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Houston, TX
  {
    id: "fb_houstontx_0",
    city: "Houston, TX",
    restaurant: "Matter Formula (Nationwide Viral — Request in Houston, TX)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Houston, TX — Comment SOS Houston, TX",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Houston, TX — Comment SOS Houston, TX",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_houstontx_1",
    city: "Houston, TX",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Houston, TX)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Houston, TX — Comment SOS Houston, TX",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Houston, TX — Comment SOS Houston, TX",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_houstontx",
    city: "Houston, TX",
    restaurant: "Be first to scout Houston, TX",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Houston, TX — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Houston, TX",
    caption: "No clean high-protein reels yet in Houston, TX — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Houston, TX",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Atlanta, GA
  {
    id: "fb_atlantaga_0",
    city: "Atlanta, GA",
    restaurant: "Matter Formula (Nationwide Viral — Request in Atlanta, GA)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Atlanta, GA — Comment SOS Atlanta, GA",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Atlanta, GA — Comment SOS Atlanta, GA",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_atlantaga_1",
    city: "Atlanta, GA",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Atlanta, GA)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Atlanta, GA — Comment SOS Atlanta, GA",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Atlanta, GA — Comment SOS Atlanta, GA",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_atlantaga",
    city: "Atlanta, GA",
    restaurant: "Be first to scout Atlanta, GA",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Atlanta, GA — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Atlanta, GA",
    caption: "No clean high-protein reels yet in Atlanta, GA — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Atlanta, GA",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Portland, OR
  {
    id: "fb_portlandor_0",
    city: "Portland, OR",
    restaurant: "Matter Formula (Nationwide Viral — Request in Portland, OR)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Portland, OR — Comment SOS Portland, OR",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Portland, OR — Comment SOS Portland, OR",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_portlandor_1",
    city: "Portland, OR",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Portland, OR)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Portland, OR — Comment SOS Portland, OR",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Portland, OR — Comment SOS Portland, OR",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_portlandor",
    city: "Portland, OR",
    restaurant: "Be first to scout Portland, OR",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Portland, OR — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Portland, OR",
    caption: "No clean high-protein reels yet in Portland, OR — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Portland, OR",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Phoenix, AZ
  {
    id: "fb_phoenixaz_0",
    city: "Phoenix, AZ",
    restaurant: "Matter Formula (Nationwide Viral — Request in Phoenix, AZ)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Phoenix, AZ — Comment SOS Phoenix, AZ",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Phoenix, AZ — Comment SOS Phoenix, AZ",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_phoenixaz_1",
    city: "Phoenix, AZ",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Phoenix, AZ)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Phoenix, AZ — Comment SOS Phoenix, AZ",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Phoenix, AZ — Comment SOS Phoenix, AZ",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_phoenixaz",
    city: "Phoenix, AZ",
    restaurant: "Be first to scout Phoenix, AZ",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Phoenix, AZ — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Phoenix, AZ",
    caption: "No clean high-protein reels yet in Phoenix, AZ — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Phoenix, AZ",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Philadelphia, PA
  {
    id: "fb_philadelphiapa_0",
    city: "Philadelphia, PA",
    restaurant: "Matter Formula (Nationwide Viral — Request in Philadelphia, PA)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Philadelphia, PA — Comment SOS Philadelphia, PA",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Philadelphia, PA — Comment SOS Philadelphia, PA",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_philadelphiapa_1",
    city: "Philadelphia, PA",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Philadelphia, PA)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Philadelphia, PA — Comment SOS Philadelphia, PA",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Philadelphia, PA — Comment SOS Philadelphia, PA",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_philadelphiapa",
    city: "Philadelphia, PA",
    restaurant: "Be first to scout Philadelphia, PA",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Philadelphia, PA — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Philadelphia, PA",
    caption: "No clean high-protein reels yet in Philadelphia, PA — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Philadelphia, PA",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Detroit, MI
  {
    id: "fb_detroitmi_0",
    city: "Detroit, MI",
    restaurant: "Matter Formula (Nationwide Viral — Request in Detroit, MI)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Detroit, MI — Comment SOS Detroit, MI",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Detroit, MI — Comment SOS Detroit, MI",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_detroitmi_1",
    city: "Detroit, MI",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Detroit, MI)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Detroit, MI — Comment SOS Detroit, MI",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Detroit, MI — Comment SOS Detroit, MI",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_detroitmi",
    city: "Detroit, MI",
    restaurant: "Be first to scout Detroit, MI",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Detroit, MI — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Detroit, MI",
    caption: "No clean high-protein reels yet in Detroit, MI — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Detroit, MI",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Minneapolis, MN
  {
    id: "fb_minneapolismn_0",
    city: "Minneapolis, MN",
    restaurant: "Matter Formula (Nationwide Viral — Request in Minneapolis, MN)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Minneapolis, MN — Comment SOS Minneapolis, MN",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Minneapolis, MN — Comment SOS Minneapolis, MN",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_minneapolismn_1",
    city: "Minneapolis, MN",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Minneapolis, MN)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Minneapolis, MN — Comment SOS Minneapolis, MN",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Minneapolis, MN — Comment SOS Minneapolis, MN",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_minneapolismn",
    city: "Minneapolis, MN",
    restaurant: "Be first to scout Minneapolis, MN",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Minneapolis, MN — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Minneapolis, MN",
    caption: "No clean high-protein reels yet in Minneapolis, MN — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Minneapolis, MN",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Charlotte, NC
  {
    id: "fb_charlottenc_0",
    city: "Charlotte, NC",
    restaurant: "Matter Formula (Nationwide Viral — Request in Charlotte, NC)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Charlotte, NC — Comment SOS Charlotte, NC",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Charlotte, NC — Comment SOS Charlotte, NC",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_charlottenc_1",
    city: "Charlotte, NC",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Charlotte, NC)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Charlotte, NC — Comment SOS Charlotte, NC",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Charlotte, NC — Comment SOS Charlotte, NC",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_charlottenc",
    city: "Charlotte, NC",
    restaurant: "Be first to scout Charlotte, NC",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Charlotte, NC — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Charlotte, NC",
    caption: "No clean high-protein reels yet in Charlotte, NC — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Charlotte, NC",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Tampa, FL
  {
    id: "fb_tampafl_0",
    city: "Tampa, FL",
    restaurant: "Matter Formula (Nationwide Viral — Request in Tampa, FL)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Tampa, FL — Comment SOS Tampa, FL",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Tampa, FL — Comment SOS Tampa, FL",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_tampafl_1",
    city: "Tampa, FL",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Tampa, FL)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Tampa, FL — Comment SOS Tampa, FL",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Tampa, FL — Comment SOS Tampa, FL",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_tampafl",
    city: "Tampa, FL",
    restaurant: "Be first to scout Tampa, FL",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Tampa, FL — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Tampa, FL",
    caption: "No clean high-protein reels yet in Tampa, FL — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Tampa, FL",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Orlando, FL
  {
    id: "fb_orlandofl_0",
    city: "Orlando, FL",
    restaurant: "Matter Formula (Nationwide Viral — Request in Orlando, FL)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Orlando, FL — Comment SOS Orlando, FL",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Orlando, FL — Comment SOS Orlando, FL",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_orlandofl_1",
    city: "Orlando, FL",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Orlando, FL)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Orlando, FL — Comment SOS Orlando, FL",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Orlando, FL — Comment SOS Orlando, FL",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_orlandofl",
    city: "Orlando, FL",
    restaurant: "Be first to scout Orlando, FL",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Orlando, FL — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Orlando, FL",
    caption: "No clean high-protein reels yet in Orlando, FL — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Orlando, FL",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Las Vegas, NV
  {
    id: "fb_lasvegasnv_0",
    city: "Las Vegas, NV",
    restaurant: "Matter Formula (Nationwide Viral — Request in Las Vegas, NV)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Las Vegas, NV — Comment SOS Las Vegas, NV",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Las Vegas, NV — Comment SOS Las Vegas, NV",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_lasvegasnv_1",
    city: "Las Vegas, NV",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Las Vegas, NV)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Las Vegas, NV — Comment SOS Las Vegas, NV",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Las Vegas, NV — Comment SOS Las Vegas, NV",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_lasvegasnv",
    city: "Las Vegas, NV",
    restaurant: "Be first to scout Las Vegas, NV",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Las Vegas, NV — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Las Vegas, NV",
    caption: "No clean high-protein reels yet in Las Vegas, NV — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Las Vegas, NV",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Sacramento, CA
  {
    id: "fb_sacramentoca_0",
    city: "Sacramento, CA",
    restaurant: "Matter Formula (Nationwide Viral — Request in Sacramento, CA)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Sacramento, CA — Comment SOS Sacramento, CA",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Sacramento, CA — Comment SOS Sacramento, CA",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_sacramentoca_1",
    city: "Sacramento, CA",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Sacramento, CA)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Sacramento, CA — Comment SOS Sacramento, CA",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Sacramento, CA — Comment SOS Sacramento, CA",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_sacramentoca",
    city: "Sacramento, CA",
    restaurant: "Be first to scout Sacramento, CA",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Sacramento, CA — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Sacramento, CA",
    caption: "No clean high-protein reels yet in Sacramento, CA — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Sacramento, CA",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },

  // Portland, ME
  {
    id: "fb_portlandme_0",
    city: "Portland, ME",
    restaurant: "Matter Formula (Nationwide Viral — Request in Portland, ME)",
    reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
    creator_handle: "@thewellroundedhuman",
    protein: "77g",
    fiber: "12g",
    calories: "680",
    sugar: "5g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Portland, ME — Comment SOS Portland, ME",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Portland, ME — Comment SOS Portland, ME",
    views: "6.2k",
    tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g High Protein Bowl (Nationwide Viral)",
    verified: true,
  },
  {
    id: "fb_portlandme_1",
    city: "Portland, ME",
    restaurant: "The Protein Shop (Nationwide Viral — Request in Portland, ME)",
    reel_url: "https://www.instagram.com/reel/DcG2f_wRc0T/",
    creator_handle: "@paola.lifts",
    protein: "77g",
    fiber: "8g",
    calories: "650",
    sugar: "6g",
    caption_for_app: "Nationwide viral 77g protein bowl — Be first to scout Portland, ME — Comment SOS Portland, ME",
    caption: "Nationwide viral 77g protein bowl — Be first to scout Portland, ME — Comment SOS Portland, ME",
    views: "8.9k",
    tags: ["high-protein", "low-sugar", "nationwide-viral", "request-city"],
    type: "fallback-nationwide",
    eating_type: "nationwide viral — eating on camera",
    thumbnail: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=800&q=80",
    dish_name: "77g Caesar Wrap (Nationwide Viral)",
    verified: true,
  },
  {
    id: "scout_portlandme",
    city: "Portland, ME",
    restaurant: "Be first to scout Portland, ME",
    reel_url: "",
    creator_handle: "@healthyvicinity",
    protein: "--",
    fiber: "--",
    calories: "--",
    sugar: "--",
    caption_for_app: "No clean high-protein reels yet in Portland, ME — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Portland, ME",
    caption: "No clean high-protein reels yet in Portland, ME — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS Portland, ME",
    views: "0",
    tags: ["scout-card", "ugc-scout"],
    type: "scout-card",
    eating_type: "placeholder",
  },
];

/**
 * Parses Instagram & Facebook URLs to return embeddable iframe URLs
 */
export function getEmbedUrl(reelUrl: string): string {
  if (!reelUrl) return "";
  if (reelUrl.includes("facebook.com")) {
    return `https://www.facebook.com/plugins/video.php?href=${encodeURIComponent(
      reelUrl
    )}&show_text=0`;
  }
  const match = reelUrl.match(/\/(?:reel|p)\/([A-Za-z0-9_-]+)/);
  if (match && match[1]) {
    const type = reelUrl.includes("/p/") ? "p" : "reel";
    return `https://www.instagram.com/${type}/${match[1]}/embed/`;
  }
  return reelUrl;
}

/**
 * Filter reels for a given city:
 * Sort order: real first, then fallback-nationwide, then scout-card last.
 * If empty, automatically returns 2 nationwide viral + 1 scout card.
 */
export function getCityReels(city: ReelCity | string, allReels: Reel[] = REELS_DATA): Reel[] {
  const normCity = (city || '').toLowerCase().trim();
  const baseCity = normCity.split(',')[0].replace(/[^a-z0-9]/g, '');

  const filtered = allReels.filter((r) => {
    if (!r.city) return false;
    const rNorm = r.city.toLowerCase().trim();
    if (rNorm === normCity) return true;

    const rBaseCity = rNorm.split(',')[0].replace(/[^a-z0-9]/g, '');
    if (baseCity && rBaseCity && (baseCity === rBaseCity || rNorm.includes(baseCity) || normCity.includes(rBaseCity))) {
      return true;
    }

    // Delhi NCR umbrella mapping
    const isDelhiNcr = (c: string) => ['delhi', 'ghaziabad', 'noida', 'gurugram'].some((ncr) => c.includes(ncr));
    if (isDelhiNcr(normCity) && isDelhiNcr(rNorm)) {
      return true;
    }

    return false;
  });

  if (filtered.length > 0) {
    return [...filtered].sort((a, b) => {
      const order = { real: 0, "fallback-nationwide": 1, "scout-card": 2 };
      return order[a.type] - order[b.type];
    });
  }

  // Fallback if none found: provide 2 nationwide viral + 1 scout card for this city
  const nationwideFallbacks: Reel[] = [
    {
      id: `fb_${city.toLowerCase().replace(/[^a-z0-9]/g, "")}_0`,
      city: city,
      restaurant: `Matter Formula (Nationwide Viral — Request in ${city})`,
      reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
      creator_handle: "@thewellroundedhuman",
      protein: "77g",
      fiber: "12g",
      calories: "680",
      sugar: "5g",
      caption_for_app: `Nationwide viral 77g protein bowl — Be first to scout ${city} — Comment SOS ${city}`,
      caption: `Nationwide viral 77g protein bowl — Be first to scout ${city} — Comment SOS ${city}`,
      views: "6.2k",
      type: "fallback-nationwide",
      tags: ["high-protein", "high-fiber", "nationwide-viral", "request-city"],
      dish_name: "77g High Protein Bowl (Nationwide Viral)",
      thumbnail: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
      verified: true,
    },
    {
      id: `fb_${city.toLowerCase().replace(/[^a-z0-9]/g, "")}_1`,
      city: city,
      restaurant: `Sweetfin Poke (Nationwide Viral — Request in ${city})`,
      reel_url: "https://www.instagram.com/reel/Dbd3FUkIupe/",
      creator_handle: "@sweetfin",
      protein: "54g",
      fiber: "9g",
      calories: "520",
      sugar: "5g",
      caption_for_app: `HIGH PROTEIN LUNCH 54g — Be first to scout ${city} — Comment SOS ${city}`,
      caption: `HIGH PROTEIN LUNCH 54g — Be first to scout ${city} — Comment SOS ${city}`,
      views: "7.3k",
      type: "fallback-nationwide",
      tags: ["high-protein", "gluten-free", "nationwide-viral", "request-city"],
      dish_name: "54g High Protein Poke Bowl (Nationwide Viral)",
      thumbnail: "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?auto=format&fit=crop&w=800&q=80",
      verified: true,
    },
    {
      id: `scout_${city.toLowerCase().replace(/[^a-z0-9]/g, "")}`,
      city: city,
      restaurant: `Be first to scout ${city}`,
      reel_url: "",
      creator_handle: "@healthyvicinity",
      protein: "--",
      fiber: "--",
      calories: "--",
      sugar: "--",
      caption_for_app: `No clean high-protein reels yet in ${city} — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS ${city}`,
      caption: `No clean high-protein reels yet in ${city} — Film yourself eating a high-protein high-fiber low-cal low-sugar bowl and tag @healthyvicinity — Comment SOS ${city}`,
      views: "0",
      tags: ["scout-card", "ugc-scout"],
      type: "scout-card",
      eating_type: "placeholder",
    },
  ];

  return nationwideFallbacks;
}

/**
 * DAILY HUNTER:
 * Searches Instagram hashtags #highprotein #highfiber #lowcalorie #healthyfood #proteinbowl + city tag,
 * filters eating on camera, >1k likes, last 7 days, validates embed ready, dedup by reel_url,
 * appends to reels array. Replaces fallback-nationwide with real when real arrives for that city.
 */
export function fetchNewReels(targetCity?: string, currentReels: Reel[] = REELS_DATA): Reel[] {
  // Discovered pool of verified high-protein/fiber eating-on-camera public Instagram reels
  const candidateHunterReels: Reel[] = [
    {
      id: "hunter_sf_1",
      city: "San Francisco, CA",
      restaurant: "Wildseed Green Kitchen",
      reel_url: "https://www.instagram.com/reel/DaTdGXYPXKF/",
      creator_handle: "@norcal_fuel",
      protein: "46g",
      fiber: "14g",
      calories: "520",
      sugar: "4g",
      caption_for_app: "San Francisco clean harvest plate — 46g plant & clean protein — eating at patio",
      caption: "San Francisco clean harvest plate — 46g plant & clean protein — eating at patio",
      views: "14.8k",
      type: "real",
      dish_name: "Super Green Protein Harvest",
      thumbnail: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
      tags: ["high-protein", "high-fiber", "san-francisco", "clean-fuel"],
      eating_type: "creator eating outside patio",
      verified: true,
    },
    {
      id: "hunter_nash_1",
      city: "Nashville, TN",
      restaurant: "Avo Clean Dining",
      reel_url: "https://www.instagram.com/reel/DW6tHeyjpPh/",
      creator_handle: "@musiccityhealth",
      protein: "48g",
      fiber: "11g",
      calories: "560",
      sugar: "5g",
      caption_for_app: "Nashville's cleanest macro lunch — 48g protein bowl — eating at counter",
      caption: "Nashville's cleanest macro lunch — 48g protein bowl — eating at counter",
      views: "9.4k",
      type: "real",
      dish_name: "High Protein Power Bowl",
      thumbnail: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
      tags: ["high-protein", "nashville", "low-sugar"],
      eating_type: "creator eating at table",
      verified: true,
    },
    {
      id: "hunter_bos_1",
      city: "Boston, MA",
      restaurant: "Life Alive Organic",
      reel_url: "https://www.instagram.com/reel/DcBz7v9xKWD/",
      creator_handle: "@boston_macros",
      protein: "52g",
      fiber: "13g",
      calories: "540",
      sugar: "4g",
      caption_for_app: "Boston clean fuel bowl 52g protein — organic greens and quinoa — eating outside",
      caption: "Boston clean fuel bowl 52g protein — organic greens and quinoa — eating outside",
      views: "11.2k",
      type: "real",
      dish_name: "Organic Superfood Grain Bowl",
      thumbnail: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
      tags: ["high-protein", "high-fiber", "boston"],
      eating_type: "creator eating on camera",
      verified: true,
    },
  ];

  const updated = [...currentReels];

  for (const candidate of candidateHunterReels) {
    if (targetCity && candidate.city !== targetCity) continue;

    // Dedup by reel_url or id
    const alreadyExists = updated.some(
      (r) => r.id === candidate.id || (r.reel_url && r.reel_url === candidate.reel_url && r.city === candidate.city)
    );
    if (!alreadyExists) {
      // Remove fallback-nationwide for that city if a real reel arrives
      const fallbackIdx = updated.findIndex(
        (r) => r.city === candidate.city && r.type === "fallback-nationwide"
      );
      if (fallbackIdx !== -1) {
        updated.splice(fallbackIdx, 1, candidate);
      } else {
        updated.unshift(candidate);
      }
    }
  }

  return updated;
}
